language: node_js
node_js:
  - 8
  - 10
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add greenkeeper-lockfile@2
  - chmod +x -R ./scripts
install: ./scripts/install_all.sh
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - ./scripts/build_all.sh
